version: '3'
services:
  node:
    volumes:
      - ./data:/root/.vertex
    ports:
      - 26657:26657
      - 26656:26656
      - 5555:5555
    build:
      context: .
      dockerfile: ./dockers/vertex.Dockerfile
    command: node
