version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  test:
    environment:
      CC_TEST_REPORTER_ID: c15d7b2d5edf0ca5a041a71d52900f892e781bf9cc01c3232ac1ce545edb2044
    working_directory: ~/liquid
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: quoine/rocksdb:latest
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache
      - run:
          name: "Create a temp directory for artifacts"
          command: mkdir -p /tmp/artifacts
      - run:
          name: Install deps
          command: go mod download
      - run:
          name: Build
          command: cd cmd && go build -o /liquid .
      - run:
          name: Test
          command: |
            go test ./... -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - coveralls/upload:
          path_to_lcov: ./c.out
          verbose: true
      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/artifacts

workflows:
  version: 2
  qws-test-deploy:
    jobs:
      - test
